# Generated by Django 5.2.7 on 2025-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
