# Generated by Django 5.2.9 on 2025-12-19 12:25

import django.db.models.deletion
import permissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('expires_at', models.DateTimeField(default=permissions.models.get_expiry_date)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user')},
            },
        ),
    ]
