# Generated by Django 5.2.9 on 2025-12-20 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharelink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.document'),
        ),
    ]
