# Generated by Django 5.2.9 on 2025-12-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='creator',
            field=models.CharField(default='Jyotirmay1'),
            preserve_default=False,
        ),
    ]
