# Generated by Django 5.2.12 on 2026-04-10 14:13

import versions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0003_version_creator_username_alter_version_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='version_vector',
            field=models.JSONField(default=versions.models.default_version_vector),
        ),
    ]
