# Generated by Django 5.2.12 on 2026-05-05 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="users",
            field=models.ManyToManyField(
                through="permissions.Permission", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
