# Generated by Django 5.2.7 on 2025-10-10 12:11

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.JSONField(default=documents.models.default_state),
        ),
    ]
