# Generated by Django 5.2.9 on 2026-01-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='authors',
        ),
    ]
