# Generated by Django 5.2.12 on 2026-04-10 13:30

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version_vector',
            field=models.JSONField(default=documents.models.default_version_vector),
        ),
    ]
