# Generated by Django 5.2.7 on 2025-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentaccess_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaccess',
            name='level',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], max_length=10),
        ),
    ]
