# Generated by Django 5.2.9 on 2025-12-17 20:43

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_sharelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='expires_at',
            field=models.DateTimeField(default=documents.models.get_expiry_date),
        ),
    ]
